---
apiVersion: v1
data:
  config.py: |
    urls=["https://httpstat.us/503", "https://httpstat.us/200"]
    request_timeout_in_seconds=30
    query_interval_in_seconds=90
    log_level="INFO"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: query-url-config
  namespace: query-url
