---
apiVersion: v1
kind: Namespace
metadata:
  name: query-url

---
apiVersion: v1
data:
  config.py: |
    urls=["https://httpstat.us/503", "https://httpstat.us/200"]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: query-url-config
  namespace: query-url
