
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: query-url
  name: query-url
  namespace: query-url
spec:
  replicas: 1
  selector:
    matchLabels:
      run: query-url
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        run: query-url
    spec:
      containers:
      - image: docker.pkg.github.com/rekhaeshwar/python-prometheus/query-url:0.0.2
        name: query-url
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        volumeMounts:
        - name: query-url-config
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
      imagePullSecrets:
      - name: git-reg-cred
      volumes:
      - name: query-url-config
        configMap:
          name: query-url-config
