---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: query-url
  name: query-url-service
  namespace: query-url
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    run: query-url
status:
  loadBalancer: {}
