---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: query-url
  name: query-url-service
  namespace: query-url
spec:
  type: ClusterIP
  ports:
  - name: webport
    port: 32000
    protocol: TCP
    targetPort: 8080
  selector:
    run: query-url
