---
apiVersion: v1
kind: Namespace
metadata:
  name: query-url

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJyZWtoYWVzaHdhciIsInBhc3N3b3JkIjoiZjY2YjRmN2M5MDBmMTk4YjI2MGViNWEzYTVlMWE4N2RjMjI3N2JlNCIsImVtYWlsIjoicmVraGFlc2h3YXJAZ21haWwuY29tIiwiYXV0aCI6ImNtVnJhR0ZsYzJoM1lYSTZaalkyWWpSbU4yTTVNREJtTVRrNFlqSTJNR1ZpTldFellUVmxNV0U0TjJSak1qSTNOMkpsTkE9PSJ9fX0=
kind: Secret
metadata:
  name: git-reg-cred
  namespace: query-url
