---
apiVersion: v1
kind: Namespace
metadata:
  name: query-url

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJyZWtoYWVzaHdhciIsInBhc3N3b3JkIjoiYjE5MjBhZmY5ZDFmNDM1MDI3MjQ5ZDdkMTgwZWEwOTUyNTVmNTNlMiIsImVtYWlsIjoicmVraGFlc2h3YXJAZ21haWwuY29tIiwiYXV0aCI6ImNtVnJhR0ZsYzJoM1lYSTZZakU1TWpCaFptWTVaREZtTkRNMU1ESTNNalE1WkRka01UZ3daV0V3T1RVeU5UVm1OVE5sTWc9PSJ9fX0=
kind: Secret
metadata:
  name: git-reg-cred
  namespace: query-url
